name: EnvironmentalEffects
version: 1.0
author: [Maxopoly]
main: com.github.maxopoly.EnvironmentalEffects
commands:
    ee:
        description: EnvironmentalEffects - Mod for creating a variety of effects
        usage: Command not found! Try /ee help

    ee reload:
        description: Completly reloads the plugin and rereads the config
        usage: /ee reload
        permission: EE.reload
    ee wrathofthegods:
        description: Brings the wrath of ttk himself upon filthy players
        usage: /ee wrathofthegods
        permission: EE.ttk
permissions:
    EE.reload:
        description: Allows player to reload the plugin by using /ee reload
        default: op 
    EE.ttk:
        description: Allows ttk to make players angry
        default: op