worldname: Zion
cancel_natural_spawns: true

weathermachines:
  global:
    rain_chance: 0.0
    minimum_rain_duration: 1d
    areas:
      biomes:
       - HELL
  hell:
    rain_chance: 0.1
    minimum_rain_duration: 3h
    areas:
      biomes:
       - EXTREME_HILLS
daytime_modifier:
  global:
    dayspeed: 0.33
    starting_time: 0
    areas:
      biomes:
       - GLOBAL

monster:
 normalsection:
  updatetime: 1m
  areas:
    biomes: 
     - EXTREME_HILLS
  mobconfig:
    zombies:
      type: ZOMBIE
      spawn_chance: 0.0666      
      identifier: zombie
      maximum_light_level: 7
    whitewalkers:
      type: ZOMBIE
      identifier: White Walker
      name: White Walker 
      spawn_chance: 0.0444
      amount: 2
      maximum_light_level: 7
      equipment:
        sword:
          material: IRON_SWORD
          enchants:
           P2:
             enchant: SWORD_DAMAGE
             level: 1
        ironchest:
           material: IRON_CHESTPLATE
           enchants:
             Prot2:
               enchant: PROTECTION_ENVIRONMENTAL
               level: 2
      buffs:
        fireres:
               type: FIRE_RESISTANCE
               level: 1
      on_hit_debuffs:
        coldtouch:
               type: SLOW
               level: 1
               duration: 5s
               chance: 1
      on_hit_message: Your body feels colder
      blocks_to_spawn_on:
         - SNOW
    skeletons:
      type: SKELETON
      spawn_chance: 0.0666
      identifier: skeleton
      maximum_light_level: 7
    spiders:
      type: SPIDER 
      spawn_chance: 0.0666
      identifier: spiders
      maximum_light_level: 7
    icespiders:
      type: SPIDER 
      spawn_chance: 0.07
      identifier: icespiders
      maximum_light_level: 7
      name: Ice Spider
      on_hit_debuffs:
         coldtouch:
           type: SLOW
           level: 1
           duration: 5s
           chance: 1
      on_hit_message: Your body feels colder
    creepers:
      type: CREEPER 
      spawn_chance: 0.0222
      identifier: creeper
      maximum_light_level: 7
    witches:
      type: WITCH
      spawn_chance: 0.0666
      identifier: witch
      maximum_light_level: 7
    enderman:
      type: ENDERMAN
      spawn_chance: 0.0111
      identifier: enderman
      maximum_light_level: 7
    chicken:
      type: CHICKEN
      spawn_chance: 0.1
      identifier: chicken
      minimum_light_level: 8
    pig:
      type: PIG
      spawn_chance: 0.1
      identifier: pig
      minimum_light_level: 8
    sheep:
      type: SHEEP
      spawn_chance: 0.05
      identifier: sheep
      minimum_light_level: 8
        
 ocean:
  updatetime: 30s
  areas:
    biomes:
     - HELL
  mobconfig:
    blaze:
      type: BLAZE
      spawn_chance: 0.1
      identifier: blazes
    pigman:
      type: PIG_ZOMBIE
      spawn_chance: 0.2
      identifier: pigman
      equipment:
        sword:
          material: GOLD_SWORD
          enchants:
              burning:
                  enchant: FIRE_ASPECT
                  level: 1
    ghast:
      type: GHAST
      spawn_chance: 0.1
      identifier: ghast
    magmacube:
      type: MAGMA_CUBE
      spawn_chance: 0.1
      identifier: magmacube